-- Add up migration script here
CREATE TABLE IF NOT EXISTS book_volumes (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "book_id" BIGINT NOT NULL,
  "name" TEXT NOT NULL,
  FOREIGN KEY ("book_id") REFERENCES books ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS book_entries (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uploader_id" BIGINT NOT NULL,
  "volume_id" BIGINT NOT NULL,
  "language" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  FOREIGN KEY ("uploader_id") REFERENCES users ("id") ON DELETE CASCADE,
  FOREIGN KEY ("volume_id") REFERENCES book_volumes ("id") ON DELETE CASCADE,
  FOREIGN KEY ("language") REFERENCES book_languages ("code") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS book_entries_uploader_volume_language_idx ON book_entries ("uploader_id", "volume_id", "language");
