name: Deploy backend
concurrency: deploy-backend-group
on:
  push:
    branches: [main]
    paths: [backend/**, .github/workflows/0-deploy-backend.yml]
jobs:
  deploy:
    name: Deploy backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy --remote-only \
            --build-secret DATABASE_URL=$DATABASE_URL
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
