name: Deploy frontend
concurrency: deploy-frontend-group
on:
  push:
    branches: [main]
    paths: [frontend/**, .github/workflows/1-deploy-frontend.yml]    
jobs:
  deploy:
    name: Deploy frontend to Cloudflare Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: ./frontend/package.json
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: "frontend"
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
        env:
          PUBLIC_CANONICAL_URL: ${{ secrets.PUBLIC_CANONICAL_URL }}
          PUBLIC_BACKEND_URL: ${{ secrets.PUBLIC_BACKEND_URL }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .svelte-kit/cloudflare --project-name=blisk --commit-dirty=true
          workingDirectory: "frontend"
